### ISSUE TITLE
(#100) Update Delivery Prescription does not work if Prescriptions are Removed 

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#59]
(#100) Update Delivery Prescription does not work if Prescriptions are Removed.

We will have delivery items that may need last minute updates. Like few items (prescriptions) deleted and new items may be added.

*Current Issues*:
1. If we have to delete an item, removing an item from the delivery prescription sending an update request is not working.
2. We need ability to patch the entire delivery request including the nested delivery prescription. 
3. Currently the patch requests are failing with 404 - record not found error.

**Comment by brprashanth** [comment]
There is still a pending issue with this. Will share the details/screenshots soon.

**Comment by brprashanth** [comment]
The items deleted are reflected. The totals are updated.
However, the prescriptions that are removed still show remain on the Deliverables List on the "Confirm Delivery Details" screen.

[After update request.txt](https://github.com/rxtrax/tracking/files/712509/After.update.request.txt)
![after update request](https://cloud.githubusercontent.com/assets/8714134/22043034/30c7b44a-dce4-11e6-8fb2-12fff64e1a68.png)

[Original Request.txt](https://github.com/rxtrax/tracking/files/712511/Original.Request.txt)
![original request](https://cloud.githubusercontent.com/assets/8714134/22043040/36bd6e3a-dce4-11e6-8b10-d04fcdab2ed9.png)

**Before**
![after 1](https://cloud.githubusercontent.com/assets/8714134/22043059/4afb647e-dce4-11e6-8c3c-b830940253ee.PNG)
![after 2](https://cloud.githubusercontent.com/assets/8714134/22043061/4afc14fa-dce4-11e6-8f60-6285e8074395.PNG)
![after 3](https://cloud.githubusercontent.com/assets/8714134/22043058/4afaadc2-dce4-11e6-9100-1998a7ae8cc9.PNG)
![after 4](https://cloud.githubusercontent.com/assets/8714134/22043060/4afbbbcc-dce4-11e6-845c-d7f009cf594e.PNG)
![after 5 total](https://cloud.githubusercontent.com/assets/8714134/22043062/4aff58b8-dce4-11e6-84fa-b8c39bdf1b7e.PNG)


**After Removing the Rxs"
![before 1](https://cloud.githubusercontent.com/assets/8714134/22043079/609f58ee-dce4-11e6-9975-7d252070767b.PNG)
![before 2](https://cloud.githubusercontent.com/assets/8714134/22043076/609e0e12-dce4-11e6-8207-5990105e000f.PNG)
![before 3](https://cloud.githubusercontent.com/assets/8714134/22043078/609ef3fe-dce4-11e6-8d68-367e5c30ab21.PNG)
![before 4](https://cloud.githubusercontent.com/assets/8714134/22043087/686d46bc-dce4-11e6-897b-860ccd812f18.PNG)
![before 5 total](https://cloud.githubusercontent.com/assets/8714134/22043094/6c3388ec-dce4-11e6-8cfe-7f55af026016.PNG)

**Comment by brprashanth** [comment]
1)	No of items are not updated. If the initial Request had 3 items (1 Rx and 2 items) ,even after deleting one item it still shows as 3 Items instead of 2 items.

![image](https://cloud.githubusercontent.com/assets/8714134/22043238/20e74dd2-dce5-11e6-9567-5564f6d6e559.png)

2)	Details in the Confirm Details window is not displaying correctly .The items are getting duplicated in place of deleted item.

![image](https://cloud.githubusercontent.com/assets/8714134/22043256/3046db62-dce5-11e6-9629-ee5b2011ca9a.png)

**Comment by jasonmadrid** [comment]
Updating a delivery with a new list of delivery-prescriptions now replaces what was there before.  `null` can now be passed to clear the delivery of any items.  This all works now with acknowledgements also.  I believe this new behavior resolves this issue.

**Comment by jasonmadrid** [comment]
Fixed in the API and on the mobile app.

**Comment by brprashanth** [comment]
Also there is an issue still. If I remove and add an Rx the QHP total that shows up on the IPAD is not latest. Added issue #143 to track this issue

RxTrax doesn't include Rx amount under QHP at the footer note on the Receipt.
**Note: This works in normal cases. However, it fails when you Remove an Rx and add a new one.**

**Steps:**
1.Add a QHP item (2.50$) to delivery transaction.
2.The receipt in the RxTrax app displays the correct QHP amount (2.50$).
3.Retrieve the receipt and add an Rx (1.00$).
4.The receipt in the RxTrax app displays the QHP amount as 2.50$. It doesn't take the Rx into consideration.

**Comment by brprashanth** [comment]
Closing this issue since we have #143 to track.
